#!/usr/bin/env python

def payloads():
    print ""
    print "Plugin Category: Payloads"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Doublepulsar      1.3.1        Remotely inject a malicious dll backdoor"
    print " Kodi              1.0.0        Create a malicious addon(backdoor) via kodi.tv"
    print " Tresspass         3.0.0        A password authenticated PHP web backdoor"
    print "\n"

def exploits():
    print ""
    print "Plugin Category: Exploits"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Eternalblue       2.2.0        Exploits a vulnerability on SMBv1/SMBv2 protocols"
    print "\n"

def others():
    print ""
    print "Plugin Category: Others"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Scan              1.0.2        Information gathering tool"
    print " jailpwn           3.1.0        Jailbroken default ssh password tool"
    print " Handler           1.0.0        Create a listener"
    print " Dnsspoof          1.0.0        DNS Spoof all http requests"
    print " Credswipe         1.0.0        A Credit Card swiper"
    print " Ftpbrute          1.2.2        Brute-force attack an ftp(file transfer protocol) server"
    print " Wifijammer        1.0.0        Deauth wifi networks around your area"
    print "\n"

def all():
    print ""
    print "Plugin Category: All"
    print "===========================================\n"
    print " Name              Version      Description"
    print " ----              -------      -----------"
    print " Scan              1.0.2        Information gathering tool"
    print " jailpwn           3.1.0        Jailbroken default ssh password tool"
    print " Eternalblue       2.2.0        Exploits a vulnerability on SMBv1/SMBv2 protocols"
    print " Doublepulsar      1.3.1        Remotely inject a malicious dll backdoor"
    print " Kodi              1.0.0        Create a malicious addon(backdoor) via kodi.tv"
    print " Tresspass         3.0.0        A password authenticated PHP web backdoor"
    print " Handler           1.0.0        Create a listener"
    print " Dnsspoof          1.0.0        DNS Spoof all http requests"
    print " Credswipe         1.0.0        A Credit Card swiper"
    print " Ftpbrute          1.2.2        Brute-force attack an ftp(file transfer protocol) server"
    print " Wifijammer        1.0.0        Deauth wifi networks around your area"
    print "\n"
